// DO NOT EDIT manually. Generated by update_notes.py
const notesConfig = [
    {
        "title": "😽 Dockerfile配置",
        "path": "docker/README.md"
    },
    {
        "title": "👿 novnc",
        "path": "docker/novnc/README.md"
    },
    {
        "title": "😨 1. test",
        "path": "emoji4md/test.md"
    },
    {
        "title": "😻 git",
        "path": "git/README.md"
    },
    {
        "title": "🤠 Linux",
        "path": "linux/README.md"
    },
    {
        "title": "😦 NeoVim",
        "path": "neovim/README.md"
    },
    {
        "title": "🤖 pip",
        "path": "pip/README.md"
    },
    {
        "title": "🥲 ROS2",
        "path": "ros/README.md"
    },
    {
        "title": "😣 SSH",
        "path": "ssh/README.md"
    },
    {
        "title": "👿 tmux 配置与使用上手指南",
        "path": "tmux/README.md"
    },
    {
        "title": "🤠 torch安装",
        "path": "torch/README.md"
    },
    {
        "title": "😶 ZSH终端配置",
        "path": "zsh/README.md"
    }
];
