#!/usr/bin/env python3
import os
import json
import re

# 忽略的目录和文件
IGNORE_DIRS = {'.git', 'docs', 'js', 'css', 'assets', 'public'}
IGNORE_FILES = {'README.md'}  # 忽略根目录的 README.md，子目录的不忽略

def get_markdown_title(filepath):
    """尝试从 markdown 文件中读取第一个一级标题作为标题，或者包含 emoji 的标题"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                if line.startswith('# '):
                    # 移除前面的 '# ' 和两端的空白
                    return line[2:].strip()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
    # 如果没找到一级标题，返回文件名
    return os.path.basename(os.path.dirname(filepath)) or os.path.basename(filepath)

def scan_notes(root_dir='.'):
    notes = []
    
    # 遍历所有子目录
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # 过滤掉隐藏目录和指定的忽略目录
        dirnames[:] = [d for d in dirnames if not d.startswith('.') and d not in IGNORE_DIRS]
        
        # 不要把根目录的 README.md 当作一篇笔记
        if dirpath == '.':
            continue
            
        for filename in filenames:
            if filename.endswith('.md'):
                filepath = os.path.join(dirpath, filename)
                rel_path = os.path.relpath(filepath, root_dir)
                
                # 为了保持统一，路径中的分隔符转换为 /
                rel_path = rel_path.replace('\\', '/')
                
                title = get_markdown_title(filepath)
                notes.append({
                    "title": title,
                    "path": rel_path
                })
                
    # 按照目录和标题排序
    notes.sort(key=lambda x: x["path"])
    return notes

def generate_config_js(notes, output_path='config.js'):
    """生成给前端使用的 JS 配置文件"""
    config_content = f"// DO NOT EDIT manually. Generated by update_notes.py\nconst notesConfig = {json.dumps(notes, ensure_ascii=False, indent=4)};\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(config_content)
    print(f"✅ 成功生成配置，共找到 {len(notes)} 篇笔记。")
    print(f"数据已写入到 {output_path}")

def update_readme(notes, readme_path='README.md'):
    """自动更新 README.md 中的笔记列表。可选。"""
    if not os.path.exists(readme_path):
        return

    try:
        with open(readme_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # 如果你的 README.md 中有特定的标识符，比如:
        # <!-- NOTES_START -->
        # ...
        # <!-- NOTES_END -->
        # 可以在这里做正则替换。如果没有的话，为了不破坏原有的结构，这里只是给出一个提示。
        print(f"💡 提示: 您可以手动将生成的笔记列表添加到 {readme_path} 中。")
    except Exception as e:
        print(f"Error updating README.md: {e}")

if __name__ == '__main__':
    print("开始扫描 Markdown 笔记...")
    notes = scan_notes('.')
    generate_config_js(notes)
    # update_readme(notes)
