#!/usr/bin/env python3
import json
import os
from pathlib import Path

# 忽略的目录和文件
IGNORE_DIRS = {'.git', 'docs', 'js', 'css', 'assets', 'public', 'scripts'}
README_FILENAME = 'README.md'
REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_OUTPUT_PATH = REPO_ROOT / 'assets' / 'js' / 'config.js'


def get_markdown_title(filepath):
    """尝试从 markdown 文件中读取第一个一级标题作为标题。"""
    try:
        with open(filepath, 'r', encoding='utf-8') as file:
            for line in file:
                if line.startswith('# '):
                    return line[2:].strip()
    except Exception as error:
        print(f"Error reading {filepath}: {error}")

    return Path(filepath).parent.name or Path(filepath).name


def scan_notes(root_dir):
    notes = []

    for dirpath, dirnames, filenames in os.walk(root_dir):
        current_dir = Path(dirpath)
        dirnames[:] = [name for name in dirnames if not name.startswith('.') and name not in IGNORE_DIRS]

        if current_dir == root_dir:
            continue

        if README_FILENAME not in filenames:
            continue

        filepath = current_dir / README_FILENAME
        rel_path = filepath.relative_to(root_dir).as_posix()

        notes.append({
            'title': get_markdown_title(filepath),
            'path': rel_path,
        })

    notes.sort(key=lambda note: note['path'])
    return notes


def generate_config_js(notes, output_path=CONFIG_OUTPUT_PATH):
    """生成给前端使用的 JS 配置文件。"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    config_content = (
        "// DO NOT EDIT manually. Generated by scripts/update_notes.py\n"
        f"const notesConfig = {json.dumps(notes, ensure_ascii=False, indent=4)};\n"
    )

    with open(output_path, 'w', encoding='utf-8') as file:
        file.write(config_content)

    print(f"✅ 成功生成配置，共找到 {len(notes)} 篇笔记。")
    print(f"数据已写入到 {output_path}")


if __name__ == '__main__':
    print('开始扫描 Markdown 笔记...')
    notes = scan_notes(REPO_ROOT)
    generate_config_js(notes)